variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - build

image: registry.gitlab.com/pages/hugo:latest

test:
  stage: test
  script:
  - hugo
  except:
  - master
  - staging

build-artifacts:
  stage: build
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  - staging

build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build-version:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
  - master
