stages:
  - test
  - build
  - deploy

image: registry.gitlab.com/pages/hugo:latest

test:
  script:
  - hugo
  except:
  - master
  - staging

build:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.andrelademann.de
  only:
  - staging

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://andrelademann.de
  when: manual
  only:
  - master