DefaultContentLanguage = "en"
baseurl = "https://hugo.andrelademann.de"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "Beautiful Hugo"
[Author]
500px = "username"
bandcamp = "username"
bitbucket = "username"
email = "youremail@domain.com"
facebook = "username"
github = "username"
gitlab = "username"
googleplus = "+username"
instagram = "username"
itchio = "username"
linkedin = "username"
name = "Some Person"
paypal = "username"
reddit = "username"
snapchat = "username"
soundcloud = "username"
spotify = "username"
stackoverflow = "users/XXXXXXX/username"
telegram = "username"
twitter = "username"
vk = "username"
website = "yourwebsite.com"
xing = "username"
youtube = "user/username"
[Params]
comments = true
commit = false
dateFormat = "January 2, 2006"
delayDisqus = true
favicon = "img/favicon.ico"
logo = "img/avatar-icon.png"
readingTime = true
rss = true
showRelatedPosts = true
socialShare = true
subtitle = "Build a beautiful and simple website in minutes"
useHLJS = true
wordCount = true
[[menu.main]]
name = "Code Sample"
parent = "samples"
url = "post/2016-03-08-code-sample"
weight = 5
[[menu.main]]
name = "Tags"
url = "tags"
weight = 4
[[menu.main]]
identifier = "samples"
name = "Samples"
weight = 3
[[menu.main]]
name = "About"
url = "page/about/"
weight = 6
[[menu.main]]
name = "Blog"
weight = 1
