DefaultContentLanguage = "en"
baseurl = "https://hugo.andrelademann.de"
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "Andre Lademann"

languages:
  en:
    languageName: English
    params:
      linkedin: "andre.lademann"
    title: My blog
    weight: 1
  de:
    languageName: Deutsch
    params:
      linkedin: "andre.lademann"
      navigation:
        help: Aide
    title: Mein Blog
    weight: 2


[Author]
github = "vergissberlin"
linkedin = "andre.lademann"
name = "Andre Lademann"
paypal = "vergissberlin"
telegram = "vergissberlin"
twitter = "vergissberlin"
xing = "andre.lademann"
youtube = "user/vergissberlin"

[Params]
comments = false
commit = false
dateFormat = "January 2, 2006"
delayDisqus = false
favicon = "img/favicon.ico"
logo = "img/avatar-icon.png"
readingTime = true
rss = true
showRelatedPosts = true
socialShare = false
subtitle = "Passion for software"
useHLJS = true
wordCount = true

[[menu.main]]
name = "Projects"
url = "projects"
weight = 2
[[menu.main]]
name = "Tags"
url = "tags"
weight = 4
[[menu.main]]
identifier = "samples"
name = "Samples"
weight = 3
[[menu.main]]
name = "About"
url = "page/about/"
weight = 6
[[menu.main]]
name = "Blog"
weight = 1
