version: '3.7'
services:
  web:
    image: vergissberlin/andrelademann-de-static
    labels:
      com.centurylinklabs.watchtower.enable: true
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30